vich_uploader:
    db_driver: orm

    mappings:
        products_image:
            uri_prefix: /uploads/product_image
            upload_destination: '%kernel.project_dir%/public/uploads/product_image'
        profile_image:
            uri_prefix: /uploads/user_image
            upload_destination: '%kernel.project_dir%/public/uploads/user_image'
